- name: redis
  ansible.builtin.include_role:
    name: geerlingguy.redis
  vars:
    redis_bind_interface: 127.0.0.1
    redis_port: 6379
    redis_requirepass: ""
    redis_maxmemory: 256mb
    redis_maxmemory_policy: allkeys-lru
    redis_appendonly: "no"
    redis_save:
      - 900 1
      - 300 10
      - 60 10000
    redis_databases: 16
