- name: restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: reloaded

- name: restart wireguard
  ansible.builtin.systemd:
    name: wg-quick@wg0
    state: restarted

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart unsafie target
  ansible.builtin.systemd:
    name: unsafie.target
    state: restarted
  ignore_errors: true
