- name: reload nginx
  ansible.builtin.command: nginx -t
  changed_when: false
  notify: reload nginx service

- name: reload nginx service
  ansible.builtin.service:
    name: nginx
    state: reloaded
