- name: restart unsafie
  ansible.builtin.command: /usr/local/bin/unsafie-reload reload
  changed_when: true

- name: reload nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded
