[cluster]
waw ansible_host=waw.unsafie.com node_id=waw node_priority=3 node_mesh_ip=10.0.0.11
de  ansible_host=de.unsafie.com  node_id=de  node_priority=2 node_mesh_ip=10.0.0.12
clt ansible_host=clt.unsafie.com node_id=clt node_priority=1 node_mesh_ip=10.0.0.13

[cluster:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
